spring:
  application:
    name: ai-bro
server:
  port: 8088
---
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/vector_store
---
spring:
  ai:
    ollama:
      init:
        pull-model-strategy: never
        chat:
          additional-models:
            - qwen2.5:7b
        embedding:
          additional-models:
            - nomic-embed-text
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b
          temperature: 0.7
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
---
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
---
logging.level.org.springframework.ai.chat.client.advisor: DEBUG
